/**
 * Created by HOZ on 28/08/2017.
 */

// define task finsh status
export const TASK_STATUS_PREPARE = 'TASK_STATUS_000'
export const TASK_STATUS_INPROCESS = 'TASK_STATUS_001'
export const TASK_STATUS_FINISHED = 'TASK_STATUS_002'
export const TASK_STATUS_UNFINISHED = 'TASK_STATUS_003'
export const TASK_STATUS_DELAYED = 'TASK_STATUS_004'
export const TASK_STATUS_URGENT = 'TASK_STATUS_005'
export const TASK_STATUS = new Map([
  [TASK_STATUS_PREPARE, '待执行'],
  [TASK_STATUS_INPROCESS, '待执行'],
  [TASK_STATUS_FINISHED, '已完成'],
  [TASK_STATUS_UNFINISHED, '未完成'],
  [TASK_STATUS_DELAYED, '延迟完成'],
  [TASK_STATUS_URGENT, '已完成']
])

export const DUTY_TIME_TYPE_ALL = 'DUTY_TIME_TYPE_ALL'
export const DUTY_CAT_PREFIX = 'DUTY_CAT_'

export const DUTY_TIME_TYPE_ROUTINE = 'DUTY_TIME_TYPE_ROUTINE'
export const DUTY_TIME_TYPE_PERIODICAL = 'DUTY_TIME_TYPE_PERIODICAL'
export const DUTY_TIME_TYPE_SPECIFIC = 'DUTY_TIME_TYPE_SPECIFIC'
export const DUTY_TIME_TYPE_GROUP = 'DUTY_TIME_TYPE_GROUP'
export const DUTY_PERIOD_TYPE_WEEK = 'DUTY_PERIOD_TYPE_WEEK'
export const DUTY_PERIOD_TYPE_MONTH = 'DUTY_PERIOD_TYPE_MONTH'
export const DUTY_PERIOD_WEEK_PREFIX = 'DUTY_PERIOD_WEEK_'
export const DUTY_PERIOD_MONTH_PREFIX = 'DUTY_PERIOD_DATE_'

export const PERMISSIONS = {
  'PERMISSION_USER_ADD': 'C_001_P_001',
  'PERMISSION_USER_REMOVE': 'C_001_P_002',
  'PERMISSION_USER_EDIT': 'C_001_P_003',
  'PERMISSION_ROLE_ADD': 'C_002_P_001',
  'PERMISSION_ROLE_REMOVE': 'C_002_P_002',
  'PERMISSION_ROLE_EDIT': 'C_002_P_003',
  'PERMISSION_TASK_QUERY_ALL': 'C_003_P_001',
  'PERMISSION_TASK_EDIT_USER_TASK': 'C_003_P_002',
  'PERMISSION_TASK_QUERY_USER_LOCATION': 'C_003_P_003',
  'PERMISSION_TASK_APPROVE_TASK': 'C_003_P_004',
  'PERMISSION_TASK_ADD_TEMP_TASK': 'C_003_P_005'
}
export const PERMISSION_CATEGORIES = {
  'PERMISSION_CATEGORY_USER': 'C_001',
  'PERMISSION_CATEGORY_ROLE': 'C_002',
  'PERMISSION_CATEGORY_TASK': 'C_003',
  'PERMISSION_CATEGORY_PERMISSIONROLE': 'C_004'
}

export const DATETYPE_DAY = 'date'
export const DATETYPE_MONTH = 'month'

export const ROOT_ROLE = '_ROLE_$_0000'

export const WEEK_DAYS = {
  '周一': 'DUTY_PERIOD_WEEK_0',
  '周二': 'DUTY_PERIOD_WEEK_1',
  '周三': 'DUTY_PERIOD_WEEK_2',
  '周四': 'DUTY_PERIOD_WEEK_3',
  '周五': 'DUTY_PERIOD_WEEK_4'
}

export const NOTIFY_TIME_TYPE = {
  'before': '开始前(分钟)',
  'after': '结束后(分钟)',
  'specific': '具体时间'
}

export const NOTIFY_TYPE = {
  'message_queue': '通知队列提醒',
  'system_alarm': '系统闹钟提醒',
  'short_message': '短信提醒'
}

export const NOTIFY_PRIORITY = {
  'high': '重要',
  'middle': '一般',
  'low': '不重要'
}

// export const MONTH_DAYS = {
//   '1': 'DUTY_PERIOD_DATE_1'
// }
